meta_product_name: "Lavender"
meta_title: "Lavender - Group Investing"
meta_description: "Create, Invest and Grow Together with Lavender Group Investing. Sign up today for commission-free stock trading ! "
meta_image: "meta_image.png" # should exist in `app/assets/images/`
